### ISSUE TITLE
Bugs in provenance

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/github-actions-demo#10]
1. `_type`: wrong capitalization: "Statement", not "statement"
1. `name` (not `Name`)
1. `digest` (not `Digest`)
1. `predicateType`: wrong capitalization: "Provenance", not "provenance"
1. `builder.id`: should identify the specific workflow that invoked the action, not github hosted actions. This represents the entity that needs to be trusted.
1. `recipe.entryPoint`: Should be "<workflow.yaml>:<job_name>", e.g. "example-publish.yaml:build"
1. `recipe.arguments`: Should be an object with an `input` field? Could you test by doing an invocation with an input? (It's OK for this to be null, but if it's not null, I think it should have an `input` field, but looking at the code I'm guessing that's not the case.)
1. `materials.uri`: protocol should be `git+https`?
1. `buildInvocationId`: Can we use a URI instead of just the number, i.e. the /runs/<runid> URI?
1. `recipe.environment`: Maybe we should just omit it since it's so huge? In reality I think GitHub would minimize the fields that are present. It's only really needed for reproducibility which is SLSA 4.

Q: Should the output be an Envelope (with no `signatures`), rather than the Statement?

**Comment by kimsterv** [comment]
On capitalization (1-3), does it matter? Is it easier to "ingorecase" on the consuming side?

**Comment by MarkLodato** [comment]
The spec says that it's case sensitive. I think that makes more sense since URIs in general are case sensitive?

**Comment by kimsterv** [comment]
Ok, is it possible to change the spec to make it lowercase since that's what they defaulted to here?

**Comment by MarkLodato** [comment]
There are already multiple implementations. I don't recommending changing the spec now.

**Comment by msuozzo** [comment]
I've marked the ones done that should be fixed by #11 

1. done
2. done
3. done
4. done
5. done
6. I don't understand this one. AFAICT, the workflow file should uniquely identify the build steps being run (esp. in multi-job workflows). What value would the job identifier provide?
7. I did add support for this. I'll get some sample output, though.
8. done
9. done
10. I don't feel strongly but I'd lean towards keeping it in. It encapsulates the environment so all we're left with is non-reproducible materials manifest (i.e. dependency+build tool tracking).

As for the envelope, I don't like that it becomes base64 encoded but it'd likely be better for future interoperability. I think ultimately, I'd prefer for it to be an Envelope but I think this works less well as a demo for understanding the system without it. Maybe we split the difference and publish both (`build.provenance` and `build.provenance.payload`?)?

**Comment by MarkLodato** [comment]
Thanks, Matt!

For 6, I'm OK omitting the job. It's a judgement call. Either way it should be the path to the workflow file. Unfortunately it looks like GitHub doesn't expose that?

For the envelope, publishing both seems like a good compromise.

**Comment by dlorenc** [comment]
> There are already multiple implementations. I don't recommending changing the spec now.

I don't have a strong opinion on casing, but now is the time we should be changing the spec. If people keep running into common issues we should use that as feedback to simplify.

**Comment by msuozzo** [comment]
eh. I'm fine keeping case sensitivity. It's a pain in golang because of the upper-case style but I blame that more on golang and if we provide a library defining the types, we can encapsulate this complexity.

**Comment by msuozzo** [comment]
> Thanks, Matt!
> 
> For 6, I'm OK omitting the job. It's a judgement call. Either way it should be the path to the workflow file. Unfortunately it looks like GitHub doesn't expose that?

I think the exposed path is relative to the workflow dir so a user should be able to reconstruct it.

> For the envelope, publishing both seems like a good compromise.

I'll do that in a follow-on change since it requires a few more changes (docs, examples, etc).

**Comment by dlorenc** [comment]
> eh. I'm fine keeping case sensitivity. It's a pain in golang because of the upper-case style but I blame that more on golang and if we provide a library defining the types, we can encapsulate this complexity.

There is a library here: https://github.com/in-toto/in-toto-golang/tree/ite-6

I don't know if it got the casing right or not though.

**Comment by msuozzo** [comment]
Yeah casing looks right. Lemme see how feasible porting to use that repo would be.

**Comment by MarkLodato** [comment]
Split out the remaining issues: #17 (recipe.arguments) and #18 (recipe.entryPoint).
