### ISSUE TITLE
Confirm that `recipe.arguments` has an `input` subfield.

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/github-actions-demo#17]
Looking at the code, it appears that the GitHub `input` object is assigned directly to `recipe.arguments` rather than `recipe.arguments.input`. @msuozzo Could you confirm with an example and fix if needed?

**Comment by msuozzo** [comment]
Confirmed working in https://github.com/slsa-framework/github-actions-demo/runs/2833147623?check_suite_focus=true
